/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Quick Start',
      collapsed: false,
      items: [
        'user-guide/install',
        'user-guide/add-media-items',
        'user-guide/create-collections',
        'user-guide/create-channels',
        'user-guide/configure-clients'
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: false,
      items: [
        'user-guide/filler',
        'user-guide/local-libraries',
        'user-guide/search',
        'user-guide/sample-schedules'
      ],
    },
    'thanks'
  ],
};

module.exports = sidebars;
